name: Black Code Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check code formatting with Black
      run: |
        black --check .
